<a href="https://colab.research.google.com/github/kiminlim/ds-section1-sprint2/blob/master/n122-chi-square-test/n122a-chi-square-test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 2 / NOTE 2*

# 📝 Assignment

In [190]:
import pandas as pd
import numpy as np


# 카이제곱검정


## 1. 공공데이터 조작 연습. 

국가 통계 포털에서 아래 이미지를 참조하여

<https://kosis.kr/statisticsList/statisticsListIndex.do?menuId=M_01_01&vwcd=MT_ZTITLE&parmTabId=M_01_01#SelectStatsBoxDiv>

**2020년 8월**에 해당하는 규모별 미분양현황 에 대한 데이터셋을 생성하세요. 

<img src='https://i.imgur.com/aZc4UJO.png' width = 500>

- `60m이하`, `60~85m`, `85m초과`의 3개 규모와 (column)
- `서울`, `대전`, `대구`, `부산` 4개의 지역을 포함해야합니다. (row)
- 데이터가 없는 경우는 0으로 처리하세요.

이후 데이터셋을 colab으로 불러오세요. 이때 변수의 이름은 `df`를 사용합니다.


In [191]:
df = pd.read_csv('/content/규모별_미분양현황_20210514161856.csv', encoding='cp949')
df

시도(1) 2020. 08 2020. 08.1 2020. 08.2 2020. 08.3 2020. 08.4
0  시도(1)     공공부문       공공부문       민간부문       민간부문       민간부문
1  시도(1)    60㎡이하     60∼85㎡      60㎡이하     60∼85㎡      85㎡초과
2     서울        0          0         54          2          0
3     부산        0          0        577        735        142
4     대구        0          0        143       1437         44
5     대전        0          0        782          1          0

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   시도(1)       6 non-null      object
 1   2020. 08    6 non-null      object
 2   2020. 08.1  6 non-null      object
 3   2020. 08.2  6 non-null      object
 4   2020. 08.3  6 non-null      object
 5   2020. 08.4  6 non-null      object
dtypes: object(6)
memory usage: 416.0+ bytes


In [193]:
col = ['~60m2', '60~85m2', '85m2~']
row = ['서울', '대전', '대구', '부산']

In [194]:
df = df.iloc[2:, 3:]
df

2020. 08.2 2020. 08.3 2020. 08.4
2         54          2          0
3        577        735        142
4        143       1437         44
5        782          1          0

In [195]:
df.index = row
df.columns = col
df

~60m2 60~85m2 85m2~
서울    54       2     0
대전   577     735   142
대구   143    1437    44
부산   782       1     0

In [196]:
df = df.apply(pd.to_numeric)

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 서울 to 부산
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ~60m2    4 non-null      int64
 1   60~85m2  4 non-null      int64
 2   85m2~    4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes


In [198]:
df.shape

(4, 3)

In [199]:
df.sum().sum()

3917

## 2. 지역에 대해서 one-sample chi-square test를 실행, 해당 결과를 `chi1`에 저장 후 설명해보세요.

예시) 만약 **9월달 데이터**를 기준으로 한다면
```python
 [0+0+0+52+2+0, 0+0+0+590+665+142, 0+0+0+113+1061+42, 0+0+0+772+1+0]
```
을 비교 하게 될 것입니다.




In [200]:

from scipy import stats
from scipy.stats import chisquare  

In [201]:
df

~60m2  60~85m2  85m2~
서울     54        2      0
대전    577      735    142
대구    143     1437     44
부산    782        1      0

In [202]:
df1 = [54+2+0, 577+735+142, 143+1437+44, 782+1+0]

In [203]:
chi1 = chisquare(df1, axis=None)
chi1.statistic
# chi1

1564.4572376818994

### 카이제곱 값이 크고, p값이 0.0 < 0.05이므로 유의수준 5%에서 귀무가설을 기각한다. 
### 즉, 서울, 대전, 대구, 부산 간의 미분양 주택 규모의 분포가 각각 다르다. 

In [204]:
# chisquare(df.loc['서울',:], axis=None)

In [205]:
# chisquare(df.loc['대전',:], axis=None)


In [206]:
# chisquare(df.loc['대구',:], axis=None)


In [207]:
# chisquare(df.loc['부산',:], axis=None)


## 3. 지역과 규모에 대해서 two-sample chi-square test를 실행, 해당 결과를 `chi2`에 저장 후 설명해보세요.

예시) **9월달 데이터**를 기준으로 한다면

| |-60 | 60-85 | 85- |
|:-:|:-:|:-:|:-:|
|서울|52|2|0|
|대전|772|1|0|
|대구|113|1061|42|
|부산|590|665|142|

에 대해서 검정해야 할 겁니다.




In [208]:
from scipy.stats import chi2_contingency

chi2 = chi2_contingency(df, correction=False)
chi2 # 카이제곱값 / 피벨류 / 자유도(4-1)*(3-1)=6 / 기대횟수 행렬

(2064.576731417199, 0.0, 6, array([[ 22.24559612,  31.09522594,   2.65917794],
        [577.59101353, 807.36533061,  69.04365586],
        [645.12228746, 901.76155221,  77.11616033],
        [311.04110288, 434.77789124,  37.18100587]]))

In [209]:
chi2[0] # 직접계산 2061.0546703932705
# 카이제곱값이 크므로 지역과 규모는 연관이 있는 것으로 보인다.

2064.576731417199

# 직접계산

In [210]:
 df1 = df

In [211]:
df1.sum(axis=1)

서울      56
대전    1454
대구    1624
부산     783
dtype: int64

In [212]:
df1.sum(axis=0)

~60m2      1556
60~85m2    2175
85m2~       186
dtype: int64

In [213]:
df1['합'] = df1.sum(axis=1)
df1 

~60m2  60~85m2  85m2~     합
서울     54        2      0    56
대전    577      735    142  1454
대구    143     1437     44  1624
부산    782        1      0   783

In [214]:
df1.loc['지역 합'] = df1.sum(axis=0) 

In [215]:
df1

~60m2  60~85m2  85m2~     합
서울       54        2      0    56
대전      577      735    142  1454
대구      143     1437     44  1624
부산      782        1      0   783
지역 합   1556     2175    186  3917

In [216]:
obs = np.array( df.iloc[:4, :3] )
obs

array([[  54,    2,    0],
       [ 577,  735,  142],
       [ 143, 1437,   44],
       [ 782,    1,    0]])

In [217]:
total_obs = np.sum(obs)
total_obs # 총합

3917

In [218]:
df1

~60m2  60~85m2  85m2~     합
서울       54        2      0    56
대전      577      735    142  1454
대구      143     1437     44  1624
부산      782        1      0   783
지역 합   1556     2175    186  3917

In [219]:
# 기대횟수 계산
exp = np.array([[ (1556*56/3917), (2175*56/3917), (186*56/3917)  ],       
                [1556*1454/3917, 2175*1454/3917, 189*1454/3917],  
                [1556*1624/3917, 2175*1624/3917, 186*1624/3917],                   
                [1556*783/3917, 2175*783/3917, 186*783/3917]], dtype = object)                     

# exp = exp / total_obs #에러나서 직접나눔 -> 해결, 하나를 더 계산해서 배열 이상해진 것이었음.
exp

array([[22.245596119479192, 31.095225938218025, 2.6591779423027826],
       [577.5910135307633, 807.3653306101609, 70.15726321164156],
       [645.1222874648967, 901.7615522083227, 77.1161603267807],
       [311.0411028848609, 434.7778912432984, 37.181005871840696]],
      dtype=object)

In [220]:
chi2 #비교

(2064.576731417199, 0.0, 6, array([[ 22.24559612,  31.09522594,   2.65917794],
        [577.59101353, 807.36533061,  69.04365586],
        [645.12228746, 901.76155221,  77.11616033],
        [311.04110288, 434.77789124,  37.18100587]]))

In [221]:
# squared = np.power(obs - exp, 2) # 제곱- 그냥 **2는?
squared = np.power(obs - exp, 2)
squared

array([[1008.342165807235, 846.532172395955, 7.071227328829661],
       [0.3492969935453591, 5236.741074317885, 5161.378829241351],
       [252126.79156898032, 286480.19599444413, 1096.680074789044],
       [221802.28277190818, 188163.25893148285, 1382.4271976418524]],
      dtype=object)

In [222]:
# 카이제곱 통계량 - 제곱한 차이들 기대횟수로 나누어서 합하기.
chi = np.sum(squared / exp)
chi # 2064.576731417199 사이파이로 구한 카이제곱값과 비슷하다. 


2061.0546703932705


---
두가지 방법으로 구한 카이제곱 값은 약 2060 정도로 이는 매우 큰 값이다. 

카이제곱 값은 귀무가설이 참이라고 가정했을 때의 기대 횟수와의 거리라고도 할 수 있다. 
위의 자료에서의 가설은 
* H0 : 지역과 규모가 연관이 없다. 
* H1 : 지역과 규모에 연관이 있다. 

위와 같다. 
계산 결과 큰 카이제곱 값이 나왔으므로 이는 귀무가설이 참이라는 것의 반대되는 증거가 된다. 

즉, 해당 데이터에 따르면 지역과 미분양된 주택에는 연관성이 높은 것으로 보여진다. 
---


### 4. 2번에 대해서 NumPy 를 사용하여 (Scipy를 사용하지 않고) $\chi^2$ test 시행 후 2번의 결과와 비교해보세요. 

- `obs`, `exp`, `chi`라는 변수를 사용해야합니다.

이 후 `chi2_contingency()`의 결과물과 비교해보세요

In [223]:
df1

~60m2  60~85m2  85m2~     합
서울       54        2      0    56
대전      577      735    142  1454
대구      143     1437     44  1624
부산      782        1      0   783
지역 합   1556     2175    186  3917

In [224]:
obs = np.array(df1)
obs

array([[  54,    2,    0,   56],
       [ 577,  735,  142, 1454],
       [ 143, 1437,   44, 1624],
       [ 782,    1,    0,  783],
       [1556, 2175,  186, 3917]])

In [225]:
exp = sum(obs) / len(obs)
exp

array([ 622.4,  870. ,   74.4, 1566.8])

In [226]:
# sum(obs) 
# len(obs)

In [227]:
chi =sum(np.power(obs - exp, 2 ) /exp )
chi

array([2332.97750643, 4081.9816092 ,  390.04301075, 5384.41077355])

In [228]:
#p값
from scipy import stats

x2 = 1564.4572376818994

1 - stats.chi.cdf(x2, df=3)

0.0

## 🔥 도전 과제

아래 세가지를 다하면 됩니다.

### 1. Function

4번에서 사용한 one sample chisquare test를 함수의 형태로 변경하세요.

In [ ]:
v1 = [18,22,20,15,23,22]
v2 = [5,23,26,19,24,23]

def myChisq(value):
    return None# 내용을 채우세요.

myChisq(v1) 

# chisquare값과 pvalue를 출력해야합니다.

myChisq(v2)

### 2. ANOVA

아래 링크를 참조하여 ANOVA 에 대한 글을 읽고

<https://partrita.github.io/posts/ANOVA-python/>

다음 `4개 그룹에 대해서 평균의 차이가 있는지`에 대한 가설 검정을 시행하세요.

A : `38 33 35 92 76 97 88 41 11  9`

B : `18 52 62 48 30 40 87 12 97 82`

C :  `28 90  5 49 66 73 96 80  4 17`

D : ` 8 99  4 12  7 64 18 10  9 20`



## 3. Sign Test

아래 링크를 참조하여 Sign Test에 대한 글을 읽고

<https://en.wikipedia.org/wiki/Sign_test>

다음 데이터에서 두 그룹간에 차이가 있다에 대한 Sign Test의 과정과 결과를 설명하세요

|A|B|
|:-:|:-:|
|142|138|
|140|136|
|144|147|	
|144|139|	
|142|143|	
|146|141|	
|149|143|	
|150|145|	
|142|136|	
|148|146|	

